# YouTube Downloader Discord Bot 設定ファイル
# このファイルをconfig.yamlにコピーして実際の値を設定してください

# Discord Bot設定
# ===========================================
# Discord Botのトークン（Discord Developer Portalで取得）
DISCORD_TOKEN: "your-discord-bot-token"

# 管理者ロール名（setlimit, changefolder等の管理コマンドを実行可能）
ADMIN_ROLE: "Admin"

# アップロード許可ロール名（upload コマンドを実行可能）
ALLOWED_ROLE: "Uploader"

# 対象サーバーID（このBotが動作するDiscordサーバーのID）
ALLOWED_GUILD_ID: 123456789012345678


# Cloudflare R2 ストレージ設定
# ===========================================
# R2バケット名
R2_BUCKET: "your-r2-bucket-name"

# R2 APIエンドポイント（アカウント固有のURL）
# 例: https://<account-id>.r2.cloudflarestorage.com
R2_ENDPOINT: "https://<account-id>.r2.cloudflarestorage.com"

# R2 APIアクセスキー
R2_ACCESS_KEY: "your-access-key"

# R2 APIシークレットキー
R2_SECRET_KEY: "your-secret-key"

# ファイル公開用のベースURL（カスタムドメインまたはR2の公開URL）
# 例: https://files.example.com
R2_PUBLIC_URL: "https://files.example.com"


# アプリケーション設定
# ===========================================
# 新規ユーザーのデフォルトアップロード上限（0=無制限）
DEFAULT_UPLOAD_LIMIT: 5


# ログ設定
# ===========================================
# コンソール出力のログレベル
# DEBUG: 詳細なデバッグ情報（開発時推奨）
# INFO: 一般的な動作情報（本番運用推奨）
# WARNING: 警告以上のみ
# ERROR: エラーのみ
CONSOLE_LOG_LEVEL: "INFO"

# ファイル出力のログレベル（通常はDEBUGに設定して詳細ログを保存）
FILE_LOG_LEVEL: "DEBUG"

# ログファイル保存ディレクトリ
LOG_DIR: "logs"